## Inverse Kinematics

### w/ Movement

In [1]:
import numpy as np
# from time import time
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import math
from drawnow import *
%matplotlib tk

In [2]:
# Length L1 ~ L3 값을 설정하세요.
L1 = 4
L2 = 3
L3 = 2
LMT = L1 + L2 + L3 +1

T = 50
dt = 1
datasize = int(T/dt)

tm = 0

fig = plt.figure(1)

T01_x = []
T01_y = []
T02_x = []
T02_y = []
T03_x = []
T03_y = []
T0H_x = []
T0H_y = []

def show_plot():
    plt.xlim(-1, LMT)
    plt.ylim(-1, LMT)
    plt.plot([T01_x, T02_x], [T01_y, T02_y], 'r')
    plt.plot([T02_x, T03_x], [T02_y, T03_y], 'g')
    plt.plot([T03_x, T0H_x], [T03_y, T0H_y], 'b')
    plt.title("Inverse Kinematics")
    
for i in range(datasize):
    phi = 90/180*np.pi
    px = 2 * np.sin(2 * np.pi * tm/2)
    py = 4
    
    T0H = np.mat([[np.cos(phi), -np.sin(phi), 0, px],
             [np.sin(phi), np.cos(phi), 0, py],
             [0, 0, 1, 0], 
             [0, 0, 0, 1]])
    
    # ---- Inverse Kinematics ----

    T3H = np.mat([[1, 0, 0, L3],
                [0, 1, 0, 0],
                [0, 0, 1, 0], 
                [0, 0, 0, 1]])

    T03 = T0H * T3H.I

    x = T03[0, 3]
    y = T03[1, 3]
    c_phi = T03[0, 0]
    s_phi = T03[1, 0]

    c2 = (x**2 + y**2 - L1**2 - L2**2) / (2 * L1 * L2)
    
    # s2 > 0
    s2 = math.sqrt(1-c2**2)

    th2 = math.atan2(s2, c2)

    k1 = L1 + L2 * c2
    k2 = L2 * s2

    K = np.mat([[k1, -k2], [k2, k1]])
    XY = np.mat([[x], [y]])

    tmp=K.I*XY

    c1 = tmp[0, 0]
    s1 = tmp[1, 0]

    th1 = math.atan2(s1, c1)

    phi = math.atan2(s_phi, c_phi)
    th3 = phi - th1 - th2

    th1_deg = th1 * 180/np.pi
    th2_deg = th2 * 180/np.pi
    th3_deg = th3 * 180/np.pi
    phi_deg = phi * 180/np.pi
    
    # ---- Forward Kinematics ----

    T01 = np.mat([[np.cos(th1), -np.sin(th1), 0, 0],
                [np.sin(th1), np.cos(th1), 0, 0],
                [0, 0, 1, 0], 
                [0, 0, 0, 1]])

    T12 = np.mat([[np.cos(th2), -np.sin(th2), 0, L1],
                [np.sin(th2), np.cos(th2), 1, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 1]])

    T23 = np.mat([[np.cos(th3), -np.sin(th3), 0, L2],
                [np.sin(th3), np.cos(th3), 0, 0],
                [0, 0, 1, 0], 
                [0, 0, 0, 1]])

    T3H = np.mat([[1, 0, 0, L3],
                [0, 1, 0, 0],
                [0, 0, 1, 0], 
                [0, 0, 0, 1]])

    T02 = T01 * T12
    T03 = T02 * T23
    T0H = T03 * T3H
    
    T01_x = np.append(T01_x, T01[0, 3])
    T01_y = np.append(T01_y, T01[1, 3])
    T02_x = np.append(T02_x, T02[0, 3])
    T02_y = np.append(T02_y, T02[1, 3])
    T03_x = np.append(T03_x, T03[0, 3])
    T03_y = np.append(T03_y, T03[1, 3])
    T0H_x = np.append(T0H_x, T0H[0, 3])
    T0H_y = np.append(T0H_y, T0H[1, 3])
    
    print(T03)
    
    drawnow(show_plot)

[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000000

[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 5.02230207e-17 -1.00000000e+00 -6.87500000e-01  0.00000000e+00]
 [ 1.00000000e+00  5.90365716e-17  7.26184377e-01  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.000000

In [ ]:
# fig = plt.figure(1)
 
# angles = []
# sines = []
# cosines = []
 
# def show_plot():
#     plt.plot(angles,sines,label='Sine')
#     plt.plot(angles,cosines,label='Cosine')
#     plt.legend()
#     plt.grid()
#     plt.xlabel('Angles [deg]')
#     plt.ylabel('Value')
    
# for x in np.linspace(0,np.pi*2,100):
#     angles = np.append(angles, x)
#     sines  = np.append(sines, np.sin(x))
#     cosines= np.append(cosines, np.cos(x))
    
#     drawnow(show_plot)

In [3]:
# sizes = 101
# x = np.linspace(-np.pi, np.pi, sizes)
# X = np.tile(x,(sizes,1))
# Y = np.transpose(X)
# Z = np.zeros((sizes,sizes),dtype='float')
 
 
# fig = plt.figure(1)
 
# def show_plot():
#     ax = fig.add_subplot(111,projection='3d')
#     ax.plot_surface(X,Y,Z)
#     ax.set_xlim((-np.pi,np.pi))
#     ax.set_ylim((-np.pi,np.pi))
#     ax.set_zlim((-1,1))
#     pan = 30
#     tilt = 60
#     ax.view_init(pan,tilt)
    
# for now in np.linspace(0,2*np.pi,100):
    
#     for ix in range(0,sizes):
#         for iy in range(0,sizes):
#             dist = np.sqrt(X[ix,iy]**2 + Y[ix,iy]**2)
#             Z[ix,iy] = np.cos((dist*3+now))*(1/(dist+1))
            
#     drawnow(show_plot)
